server:
  #address: localhost
  #address: 192.168.45.145
  port: 8080
  servlet:
    context-path: /publisher

spring:
  config.activate.on-profile: test

  main:
    #allow-bean-definition-overriding: true
    allow-circular-references: true

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
      serialization:
        indent-output: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://127.0.0.1:3306/publisher_test?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: root
    password: root
    hikari:
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  liquibase:
    contexts: dev

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      #hibernate.dialect: org.esupportail.publisher.utils.MySQL5InnoDBCompressedDialect

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false

logging:
  config: "classpath:logback-test.xml"

app:
  service:
    classification-params:
      highlight-classification :
        name: "À la une"
        color: "#F44336"
        description: "Rubrique contenant les publications à mettre en avant"
      defaultTTL: 3600
      default-timeout: 15000
  security:
    #auth-uri-filter-path: j_spring_cas_security_check
    #redirect-param-name: spring-security-redirect
    #security: http://192.168.45.170:8080/j_spring_cas_security_check
    authorized-domain-names:
      - http://localhost:8080
      - http://192.168.45.170:8080
      - http://192.168.36.5:8080
      - http://192.168.36.6:8080
      - http://192.168.2.79:8080
    protocol: http://
    id-key-provider: esco_cas_publisher
    soffit-jwt-signing-key: changeme
  cas:
    url-prefix: https://secure.giprecia.net/cas_old/
    url-login: https://secure.giprecia.net/cas_old/login
    url-logout: https://secure.giprecia.net/cas_old/logout
  ldap:
    context-source:
      base: dc=esco-centre,dc=fr
      urls:
        - ldap://127.0.0.1:389/
      username: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
      password: admin
      anonymous-read-only: false
      native-pooling: false
    ldap-template:
      count-limit: 20000
      time-limit: 20000
    user-branch:
      other-displayed-attributes: mail,ESCOUAI, ENTPersonProfils
      other-backend-attributes: isMemberOf, ENTPersonProfils, ESCOPersonProfils, ENTPersonJointure, ESCOUAICourant, ESCOSIRENCourant
    group-branch:
      dn-contains-display-name: true
      group-member-key-pattern: "cn=(.*),ou=groups,dc=esco-centre,dc=fr"
      group-member-key-pattern-index: 1
      user-member-key-pattern: "uid=(.*),ou=people,dc=esco-centre,dc=fr"
      user-member-key-pattern-index: 1
      group-display-name-pattern: ".*:([^:]*)"
      resolve-user-members: true
      resolve-user-members-by-user-attributes: true
      # designers can be commented - used to attach groups that are not in the tree root or membrers on
      designers:
        - group-root-pattern: "((esco)|(cfa)|(clg[0-9]{2})|(agri)):Etablissements:[^:]*"
          group-attach-end-match: ":Profs"
          group-to-attach-end-pattern: ":*:Profs_*,:*:Profs Principaux"
        - group-root-pattern: "ef2s:Etablissements:[^:]*"
          group-attach-end-match: ":Formateurs"
          group-to-attach-end-pattern: ":*:Formateurs_*, :*:Responsable de formation"
        - group-root-pattern: "((esco)|(cfa)|(clg[0-9]{2})|(agri)):Inter_etablissements"
          group-attach-end-match: ":Tous_Profils_Etablissements"
          group-to-attach-end-pattern: ":Tous_Profs,:Tous_Administratifs,:Tous_Eleves,:Tous_Parents,:Tous_Agents_Coll_Ter"
      # for formatters can be commented
      name-formatters:
        - group-matcher: "((esco)|(cfa)|(clg[0-9]{2})|(agri)|(ef2s)):Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:groupes_locaux:Publication_contenus"
          group-name-regex: "[^:]+:Etablissements:([^:]+)_[0-9]{7}[a-zA-Z]{1}:(groupes_locaux):Publication_contenus"
          group-name-index: "2,1"
          group-recomposer-separator: " - "
        - group-matcher: "((esco)|(cfa)|(clg[0-9]{2})|(agri)):Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:[^:]+:Profs Principaux"
          group-name-regex: "[^:]+:Etablissements:[^:]+:([^:]+):(Profs Principaux)"
          group-name-index: "2,1"
          group-recomposer-separator: " - "
        - group-matcher: "ef2s:Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:[^:]+:Responsable de formation"
          group-name-regex: "ef2s:Etablissements:[^:]+:([^:]+):(Responsable de formation)"
          group-name-index: "2,1"
          group-recomposer-separator: " - "
        - group-matcher: "agri:Inter_etablissements:Tous_Profils_Etablissements"
          group-name-regex: "agri:Inter_etablissements:(Tous_Profils_Etablissements)"
          group-name-index: "1"
          group-recomposer-separator: " "
          group-suffixe-to-append: " EA"
        - group-matcher: "esco:Inter_etablissements:Tous_Profils_Etablissements"
          group-name-regex: "esco:Inter_etablissements:(Tous_Profils_Etablissements)"
          group-name-index: "1"
          group-recomposer-separator: " "
          group-suffixe-to-append: " EN"
      dont-resolve-members-with-group-pattern:
        "((agri)|(esco)|(clg[0-9]{2})):Inter_etablissements:Tous_((Profs)|(Administratifs)|(Eleves)|(Parents)|(Agents_Coll_Ter)|(Profils_Etablissements))"
  cache:
    time-to-live-seconds: 3600
    max-entries: 1000

  admins:
    user-name: admin
    group-name: "esco:admin:central"

  users:
    group-name: "((esco)|(cfa)|(clg[0-9]{2})|(agri)|(coll)|(ef2s)):admin:Publication_contenus:.*"

  mail:
    base-url: http://localhost:8080
    from: publisher@localhost
  cors:
    allowed-origins: "*"

  upload:
    path: "/home/jgribonvald/tmp/"
    # 128Kb max
    image-max-size: 131072
    protected-path: "/home/jgribonvald/tmp/"
    # not needed anymore: file-path-of-authorized-mime-types: "MimeTypes.txt"
    # 10MB max should be equals or lower than spring.servlet.multipart.maxFileSize
    max-file-size: 10485760
    unremovable-path-pattern:
      - "default/welcome.*"
      - "test.*"

  authorized-services:
    #ip-ranges: "192.168.45.0/24"
    ip-ranges:
      - "192.168.0.0/16"

  metrics:
    prometeus-authorized-acess:
      ip-ranges:
        - "192.168.0.0/16"

  ckeditor:
    media-embed:
      media-url-pattern: /^(?:(?:https?:)?\/\/)?(pod\.univ\.fr\/video|.*\.fr\/POD\/video)\/(.*)\/(\?is_iframe=true)?$/

  injected:
    web-components:
